display-demo: board/xplain/include/board/spi.h File Reference
board/xplain/include/board/spi.h File Reference
Board-specific SPI control.
#include <gpio.h>
Data Structures
struct board_spi_select
Board SPI select struct.
Typedefs
typedef enum board_spi_select_id board_spi_select_id_t
Board SPI select identifier type.
Enumerations
enum board_spi_select_id
Board SPI select identifiers.
Functions
static void board_spi_select_device (struct spi_master *master, struct board_spi_select *sel)
Board SPI select given device.
static void board_spi_deselect_device (struct spi_master *master, struct board_spi_select *sel)
Board SPI deselect given device.
static void board_spi_init_select (struct board_spi_select *sel, board_spi_select_id_t sel_id)
Init Board SPI select.
Detailed Description
Board-specific SPI control.
Copyright (C) 2009 Atmel Corporation. All rights reserved.
Definition in file spi.h.
Typedef Documentation
typedef enum board_spi_select_id board_spi_select_id_t
Board SPI select identifier type.
Definition at line 50 of file spi.h.
Enumeration Type Documentation
enum board_spi_select_id
Board SPI select identifiers.
Definition at line 44 of file spi.h.
Function Documentation
static void board_spi_deselect_device (struct spi_master * master, struct board_spi_select * sel) [inline, static]
Board SPI deselect given device.
Parameters:
master SPI master struct
sel Board SPI select struct
Definition at line 76 of file spi.h.
References gpio_set_value(), and board_spi_select::pin.
static void board_spi_init_select (struct board_spi_select * sel, board_spi_select_id_t sel_id) [inline, static]
Init Board SPI select.
Parameters:
sel Board SPI select struct
sel_id Board SPI select identifier
Definition at line 88 of file spi.h.
References board_spi_select::pin, PORT_DIR_OUTPUT, PORT_INIT_HIGH, and port_select_gpio_pin().
static void board_spi_select_device (struct spi_master * master, struct board_spi_select * sel) [inline, static]
Board SPI select given device.
Parameters:
master SPI master struct
sel Board SPI select struct
Definition at line 64 of file spi.h.
References gpio_set_value(), and board_spi_select::pin.