display-demo: Memory Pool Allocator
Memory Pool Allocator
[Memory Allocation]
Data Structures
struct mem_pool
Memory pool.
Functions
void mem_pool_init (struct mem_pool *pool, void *start, size_t size, size_t objsize, unsigned int align_order)
Initialize a memory pool.
void mem_pool_init_physmem (struct mem_pool *mempool, struct physmem_pool *phys_pool, unsigned int nr_objects, size_t objsize, unsigned int align_order)
Initialize a memory pool using the physmem allocator.
void * mem_pool_alloc (struct mem_pool *pool)
Allocate an object from a memory pool.
void mem_pool_free (struct mem_pool *pool, const void *obj)
Free an object previously allocated from a memory pool.
Detailed Description
A memory pool contains a number of objects of the same size that can be allocated in constant time. This is useful for allocating request structures, etc.
Memory pool objects are managed in Last-In-First-Out (LIFO) order to maximize the chances of allocating a cache-hot object.
Function Documentation
void * mem_pool_alloc (struct mem_pool * pool)
Allocate an object from a memory pool.
Parameters:
pool The memory pool from which the object is allocated.
Returns:
A pointer to the newly allocated object, or NULL if the pool is exhausted.
Referenced by buffer_alloc(), dataflash_alloc_req(), and membag_alloc().
void mem_pool_free (struct mem_pool * pool, const void * obj)
Free an object previously allocated from a memory pool.
The caller is responsible for making sure obj was originally allocated from pool. If an object is freed into a different pool, the integrity of the pool can no longer be guaranteed.
Note:
The object ceases to exist the moment this function is called, so even though this function casts away the const qualifier internally, it doesn't technically modify the object. Having the const qualifier there allows callers to keep const pointers to objects which are never modified after initialization. Objects stored in flash should obviously never be freed.
Parameters:
pool The memory pool which the object belongs to.
obj The object to be freed.
Referenced by buffer_free(), dataflash_free_req(), and membag_free().
void mem_pool_init (struct mem_pool * pool, void * start, size_t size, size_t objsize, unsigned int align_order)
Initialize a memory pool.
This function will initialize a memory pool, populating its freelist with objects tightly packed into the specified memory range.
All objects in the pool are guaranteed to be aligned to a multiple of bytes. For example, if align_order is 4, each object will start on a 16-byte boundary.
Parameters:
pool The memory pool to be initialized.
start The memory area to be used for object storage.
size The size of the memory area in bytes.
objsize The size of each object in bytes.
align_order log2 of the minimum object alignment in bytes.
Precondition:
objsize must be larger than the size of a pointer.
size must be large enough to hold at least one object.
Referenced by membag_pool_init_physmem().
void mem_pool_init_physmem (struct mem_pool * mempool, struct physmem_pool * phys_pool, unsigned int nr_objects, size_t objsize, unsigned int align_order)
Initialize a memory pool using the physmem allocator.
This function will grab enough physical memory for nr_objects and use this to initialize mempool.
Parameters:
mempool The memory pool to be initialized.
phys_pool The physical memory pool from which to grab memory
nr_objects The number of objects in the pool
objsize The size of each object in bytes.
align_order log2 of the minimum object alignment in bytes.
Precondition:
nr_objects must be at least one.
There must be enough available memory in phys_pool.
objsize must be larger than the size of a pointer.
See also:
mem_pool_init()
Referenced by buffer_pool_init().