xplain-bc: apps/xplain-bc/dataflash.c File Reference
apps/xplain-bc/dataflash.c File Reference
DataFlash and USB configuration and initialization.
#include <usb/dev_mux.h>
#include <usb/udi_msc_bulk.h>
#include <block/dataflash.h>
#include "xplain-bc.h"
Functions
void dataflash_init (struct app_usb_mode_task *usb_mode_task)
Initialize the USB interface and the DataFlash block driver.
Detailed Description
DataFlash and USB configuration and initialization.
Copyright (C) 2009 - 2010 Atmel Corporation. All rights reserved.
Definition in file dataflash.c.
Function Documentation
void dataflash_init (struct app_usb_mode_task * usb_mode_task)
Initialize the USB interface and the DataFlash block driver.
This function will initialize the SPI master, an SPI device, an USB configuration and an USB interface. These instances are then used to setup the DataFlash device, create a block device and eventually share the block device through the USB mass-storage interface.
Definition at line 51 of file dataflash.c.
References dataflash_blkdev_init(), spi_device_get_base(), spi_enable(), spi_master_get_base(), spi_master_init(), spi_master_setup_device(), SPI_MODE_0, udm_config_add_interface(), udm_config_set_bus_powered(), udm_config_set_max_power(), and udm_create_config().
Referenced by main().