/**
 * \file
 *
 * \brief Basic frame widget implementation
 *
 * Copyright (C) 2010 Atmel Corporation. All rights reserved.
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 * Atmel AVR product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */
#include <stdint.h>
#include <stdlib.h>
#include <assert.h>
#include <membag.h>
#include <string.h>
#include <gfx/wtk.h>
#include <mainloop.h>

/**
 * \brief Event command ID for the application widgets.
 *
 * \note The command IDs cannot be 0, since this value is reserved for no
 * command event callback for certain widgets.
 */
enum app_widget_ids {
	//! Event command ID for the OK button.
	BUTTON_OK_ID = 1,
};

/**
 * \ingroup gfx_wtk_basic_frame
 * @{
 */

/**
 * \brief Basic frame control struct
 *
 * This is the basic frame control struct. It contains references to the window
 * composing the frame, as well as non-window information required.
 *
 * \internal
 * \note Structure fields are only internally accessible, only pointers to
 *       structure is needed externally.
 */
struct wtk_dialogue_box {
	//! Copy of caption string.
	char                    *caption;
	//! Custom command data, used when "clicked".
	win_command_t           command_data;
};


/**
 * \brief Frame command events handler
 *
 * This function handles the command events generated by the widgets.
 *
 * \sa wtk_basic_frame_command_handler_t
 */
static bool dialogue_box_command_handler(struct wtk_basic_frame *frame,
		win_command_t command_data)
{
	char command = (char)(uintptr_t)command_data;

	struct wtk_dialogue_box *dialogue_box;
	dialogue_box = (struct wtk_dialogue_box*) 
			wtk_basic_frame_get_custom_data(frame);

	switch (command) {
	case BUTTON_OK_ID:

		win_grab_pointer(NULL);

		struct win_window *dialogue_parent = 
				win_get_parent(wtk_basic_frame_as_child(frame));

		struct win_command_event send_command;

		/*Send the supplied command event to the frame from which the 
		 *dialogue box originated
		 */

		send_command.sender = dialogue_parent;
		send_command.recipient = dialogue_parent;
		send_command.data = dialogue_box->command_data;

		win_queue_command_event(&send_command);

		//free memory of button, frame, and box.
		win_destroy(wtk_basic_frame_as_child(frame));
		membag_free(dialogue_box);

		break;
	}

	return false;
}




/**
 * \brief Create dialogue box widget
 *
 * This function creates a new dialogue box widget. It allocates required memory
 * and intializes necessary windows to create the widget. If there is not enough
 * memory, the function returns NULL.
 *
 * To destroy the widget and all its contents, and free its memory, call
 * win_destroy() on the basic frame's child reference, given by
 * wtk_basic_frame_as_child(), like this:
 * "win_destroy(wtk_basic_frame_as_child(my_frame_ptr));".
 *
 * \param parent         Parent window.
 * \param area           Area of the internal contents.
 * \param background     Pointer to background bitmap for frame. NULL for
 *                       transparent background. When background is transparent
 *                       the parent window will automatically be redrawn
 *                       when the basic frame is drawn.
 * \param draw_handler   Draw event handler. NULL for no handler.
 * \param frame_handler  Command event handler. NULL for no handler.
 * \param custom_data    Optional custom data link for application's command
 *                       events.
 *
 * \return Pointer to basic frame, or NULL if failed.
 */
struct wtk_dialogue_box *wtk_dialogue_box_create(struct win_window *parent,
		char *caption, win_command_t command_data)
{
	struct wtk_dialogue_box     *dialogue_box;
	struct wtk_button           *button_ok;
	struct wtk_basic_frame      *dialogue_frame;
	struct win_area             area;

	assert(area);
	assert(parent);

	// Allocate memory for frame control data.
	dialogue_box = membag_alloc(sizeof(struct wtk_dialogue_box));
	if (!dialogue_box) {
		goto outofmem_dialogue_box;
	}

	dialogue_box->command_data = command_data;
	dialogue_box->caption = caption;

	area.pos.x = 0;
	area.pos.y = 0;
	area.size.x = gfx_get_width();
	area.size.y = gfx_get_height();
	
	dialogue_frame = wtk_basic_frame_create(parent, &area,
			NULL, NULL, dialogue_box_command_handler, dialogue_box);
	if (!dialogue_frame) {
		goto outofmem_frame;
	}
	
	//TODO: FIKS DISSE!					NEIN!					UFFOGHUFF
	area.pos.x = gfx_get_width()/3;
	area.pos.y = gfx_get_height()/3;
	area.size.x = gfx_get_width()/4;
	area.size.y = gfx_get_height()/5;

	button_ok = wtk_button_create(wtk_basic_frame_as_child(dialogue_frame), 
			&area, "OK", (win_command_t)BUTTON_OK_ID);
	if (!button_ok) {
		goto error_widget;
	}

	win_show(wtk_basic_frame_as_child(dialogue_frame)); 


	//TODO: FIKS DISSE!					NEIN!					UFFOGHUFF
	gfx_draw_filled_rect(gfx_get_width()/5,
		gfx_get_height()/6,
		gfx_get_width()/2,
		gfx_get_height()/2, GFX_COLOR(200, 200, 200));

	
	win_show(wtk_button_as_child(button_ok));

	return dialogue_box;

error_widget:
	win_destroy(wtk_basic_frame_as_child(dialogue_frame));
outofmem_frame:
	membag_free(dialogue_box);
outofmem_dialogue_box:
	return NULL;
}

//! @}
