/**
 * \file
 *
 * \brief Basic frame widget implementation
 *
 * Copyright (C) 2010 Atmel Corporation. All rights reserved.
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 * Atmel AVR product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */
#include <stdint.h>
#include <stdlib.h>
#include <assert.h>
#include <membag.h>
#include <string.h>
#include <gfx/wtk.h>

/**
 * \brief Event command ID for the application widgets.
 *
 * \note The command IDs cannot be 0, since this value is reserved for no
 * command event callback for certain widgets.
 */
enum app_widget_ids {
	
	//! Event command ID for the OK button.
	BUTTON_OK_ID = 1,
	//! Event command ID for the Cancel button.
	BUTTON_CANCEL_ID = 2,
};

/**
 * \ingroup gfx_wtk_basic_frame
 * @{
 */

/**
 * \brief Basic frame control struct
 *
 * This is the basic frame control struct. It contains references to the window
 * composing the frame, as well as non-window information required.
 *
 * \internal
 * \note Structure fields are only internally accessible, only pointers to
 *       structure is needed externally.
 */
struct wtk_dialogue_box {
	//! Frame window.
	struct win_window					*win;

	struct win_window					*container;
	
	struct workqueue_task				*task;
	
	//! Frame command event handler.
	wtk_dialogue_box_command_handler_t	frame_handler;
	//! Data for applications and handlers.
	void								*custom_data;
	//! Frame draw event handler.
	wtk_dialogue_box_draw_handler_t		draw_handler;

};


/**
 * \brief Frame command events handler
 *
 * This function handles the command events generated by the widgets.
 *
 * \sa wtk_basic_frame_command_handler_t
 */
static bool dialogue_box_command_handler(struct wtk_dialogue_box *frame,
		win_command_t command_data)
{
	char command = (char)(uintptr_t)command_data;
	
	struct wtk_dialogue_box  *dialogue_box;
	
	switch (command) {
	case BUTTON_OK_ID:
		
		membag_free(dialogue_box);
		
		win_redraw(win_get_parent(frame->container));

        workqueue_add_task(&main_workqueue, dialogue_box->task);
		
		break;

	case BUTTON_CANCEL_ID:
		
		membag_free(dialogue_box);
		
		win_redraw(win_get_parent(frame->container));
		
		break;
	}

	return false;
}


/**
 * \brief Get reference to basic frame window.
 *
 * This function returns a reference to the window that should be used when
 * managing the widget, such as move, resize, destroy and reparenting.
 *
 * \param basic_frame Basic frame widget to manage.
 *
 * \return Window to be used for managing the basic frame.
 */
struct win_window *wtk_dialogue_box_as_child(struct wtk_dialogue_box *dialogue_box)
{
	assert(dialogue_box);
	return dialogue_box->win;
}

/**
 * \brief Get basic frame custom data
 *
 * This function returns the custom data from the basic frame's attributes.
 * The custom data can be used for e.g. linking to associated applications.
 *
 * \param basic_frame Pointer to basic frame.
 *
 * \return Copy of the custom data.
 */
void *wtk_dialogue_box_get_custom_data(const struct wtk_dialogue_box *dialogue_box)
{
	assert(dialogue_box);
	return dialogue_box->custom_data;
}

/**
 * \brief Basic frame event handler
 *
 * This function is the window event handler for basic frame widgets.
 * It handles all events sent to the windows composing the widget.
 *
 * \param win  Window receiving the event.
 * \param type The event type.
 * \param data Custom data, depending on event type.
 *
 * \return True if the event was recognized and accepted.
 */
static bool wtk_dialogue_box_handler(struct win_window *win,
		enum win_event_type type, const void *data)
{
	// Custom data for windows of a widget points back to the widget itself.
	struct wtk_dialogue_box *frame;
	bool should_destroy;
	struct win_clip_region const *clip;

	frame = win_get_custom_data(win);

	switch (type) {
	case WIN_EVENT_DRAW:
		/* For DRAW events, the data parameter points to the
		 * clipping region.
		 */
		clip = (struct win_clip_region const *)data;

		// win_grab_pointer(frame->container);

		struct wtk_button			*button_ok;
		struct win_attributes		attr;
		
			// Create the button
		attr.area.pos.x = gfx_get_width()/3;
		attr.area.pos.y = gfx_get_height()/2;
		attr.area.size.x = gfx_get_width()/3;
		attr.area.size.y = gfx_get_height()/4;

		button_ok = wtk_button_create(getparent(frame), &attr.area, "OK",
				(win_command_t)BUTTON_OK_ID);
		if (!button_ok) {
			goto error_widget;
		}
		
		win_show(wtk_button_as_child(button_ok));
		
		if (win == frame->win) {
			if (frame->draw_handler) {
				// Call the draw handler
				frame->draw_handler(win, clip);
			}
		}
		/* Always accept DRAW events, as the return value is
		 * ignored anyway for that event type.
		 */
		return true;

	case WIN_EVENT_POINTER:
		/* Accept all POINTER events so that it does not
		 * propagate up the window tree to our parent in case
		 * we did not click anything useful inside the frame.
		 */
		return true;

	case WIN_EVENT_DESTROY:
		/* When the frame window is destroyed, also destroy
		 * the rest of the non-window frame allocations.
		 */
		if (win == frame->win) {
			/* Memory allocated for windows will be
			 * automatically destroyed by the window
			 * system. We must destroy other allocations.
			 */
			membag_free(frame);
		}

		/* Always accept DESTROY events, as the return value is
		 * ignored anyway for that event type.
		 */
		return true;

	case WIN_EVENT_COMMAND:
		/* When commands are received either directly or
		 * propagated from child widgets and windows, send it
		 * to the frame handler.
		 */
		if (win == frame->win) {
			if (frame->frame_handler) {
				/* If the frame handler returns true,
				 * it wants us to destroy the frame.
				 * This is normally used by CLOSE
				 * buttons.
				 */
				should_destroy = frame->frame_handler(frame,
						(win_command_t)data);

				/* It is safe to destroy it here, since
				 * the event handling finished right
				 * after this handler returns, and no
				 * other references to this frame or
				 * its contents will be done.
				 */
				if (should_destroy) {
					win_destroy(frame->win);
				}

				/* Accept the event if there was a
				 * handler installed.
				 */
				return true;
			}
		}

		/* Reject the event if there was no handler, or this
		 * was not the container window at all.
		 */
		return false;

	default:
		// Reject unknown event types.
		return false;

	}
}

/**
 * \brief Create basic frame widget
 *
 * This function creates a new basic frame widget. It allocates required memory
 * and intializes necessary windows to create the widget. If there is not enough
 * memory, the function returns NULL.
 *
 * To destroy the widget and all its contents, and free its memory, call
 * win_destroy() on the basic frame's child reference, given by
 * wtk_basic_frame_as_child(), like this:
 * "win_destroy(wtk_basic_frame_as_child(my_frame_ptr));".
 *
 * \param parent         Parent window.
 * \param area           Area of the internal contents.
 * \param background     Pointer to background bitmap for frame. NULL for
 *                       transparent background. When background is transparent
 *                       the parent window will automatically be redrawn
 *                       when the basic frame is drawn.
 * \param draw_handler   Draw event handler. NULL for no handler.
 * \param frame_handler  Command event handler. NULL for no handler.
 * \param custom_data    Optional custom data link for application's command
 *                       events.
 *
 * \return Pointer to basic frame, or NULL if failed.
 */
struct wtk_dialogue_box *wtk_dialogue_box_create(struct win_window *parent,
		const struct win_area *area, void *custom_data, struct workqueue_task *task)
{
	struct win_attributes		attr;
	struct wtk_dialogue_box		*dialogue_box;

	
	

	assert(area);
	assert(parent);

	// Allocate memory for frame control data.
	dialogue_box = membag_alloc(sizeof(struct wtk_dialogue_box));
	if (!dialogue_box) {
		goto outofmem_dialogue_box;
	}

	// Set window attributes
	dialogue_box->frame_handler = dialogue_box_command_handler;
	dialogue_box->custom_data = custom_data;
	dialogue_box->task = task;

	// Copy area info
	// attr.area = *area;
	attr.area.pos.x = 0;
	attr.area.pos.y = 0;
	attr.area.size.x = gfx_get_width();
	attr.area.size.y = gfx_get_height();
	attr.event_handler = wtk_dialogue_box_handler;
	attr.custom = dialogue_box;

	
	// Set background for window
	// attr.background = NULL;
	
	/*if (background) {
		attr.background = background;
		attr.behavior = 0;
	} else {
		attr.background = NULL;
		attr.behavior = WIN_BEHAVIOR_REDRAW_PARENT;
	}*/

	// Create the window
	dialogue_box->win = win_create(parent, &attr);
	if (!dialogue_box->win) {
		goto outofmem_win;
	}
	


	return dialogue_box;

error_widget:
	win_destroy(wtk_dialogue_box_as_child(dialogue_box));	
	
outofmem_win:
	membag_free(dialogue_box);

outofmem_dialogue_box:
	return NULL;
}

//! @}
