display-training: drivers/gfx/hx8347a/gfx_hx8347a.c File Reference
drivers/gfx/hx8347a/gfx_hx8347a.c File Reference
Implementation of graphics routines for HX8347A compatible displays.
#include <clk/sys.h>
#include <gpio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <delay.h>
#include <assert.h>
#include <gfx/gfx.h>
#include "hx8347a_regs.h"
Functions
static void gfx_set_register (uint8_t address, uint8_t bitmask)
static void gfx_clear_register (uint8_t address, uint8_t bitmask)
static void gfx_reset_display (void)
static void gfx_exit_standby (void)
static void gfx_display_init_all (void)
void gfx_init (void)
Initialize the low-level graphics device driver.
void gfx_sync (void)
Synchronize access to the display.
void gfx_set_clipping (gfx_coord_t min_x, gfx_coord_t min_y, gfx_coord_t max_x, gfx_coord_t max_y)
Set the clipping region.
void gfx_set_orientation (uint8_t flags)
Change display orientation.
gfx_coord_t gfx_get_width (void)
Return the current width of the screen.
gfx_coord_t gfx_get_height (void)
Return the current height of the screen.
gfx_color_t gfx_color (uint8_t r, uint8_t g, uint8_t b)
Generate native color value from R/G/B values.
gfx_color_t gfx_get_pixel (gfx_coord_t x, gfx_coord_t y)
Get the color of a pixel on the display.
void gfx_draw_pixel (gfx_coord_t x, gfx_coord_t y, gfx_color_t color)
Draw a single pixel on the screen.
void gfx_draw_line_pixel (gfx_coord_t x, gfx_coord_t y, gfx_color_t color)
Draw a single pixel on the screen (for lines, apparently).
void gfx_set_top_left_limit (gfx_coord_t x, gfx_coord_t y)
Set the top-left limit for the display.
void gfx_set_bottom_right_limit (gfx_coord_t x, gfx_coord_t y)
Set the bottom-right limit for the display.
void gfx_set_limits (gfx_coord_t x1, gfx_coord_t y1, gfx_coord_t x2, gfx_coord_t y2)
Set the limits for the display.
Variables
gfx_coord_t gfx_width
Current width of screen.
gfx_coord_t gfx_height
Current height of screen.
Detailed Description
Implementation of graphics routines for HX8347A compatible displays.
Copyright (C) 2009 - 2010 Atmel Corporation. All rights reserved.
Definition in file gfx_hx8347a.c.
Function Documentation
static void gfx_clear_register (uint8_t address, uint8_t bitmask) [static]
For internal use only.
Read-modify-write shortcut to clear bits in a register.
Definition at line 80 of file gfx_hx8347a.c.
References gfx_read_register(), and gfx_write_register().
Referenced by gfx_exit_standby().
static void gfx_display_init_all (void) [static]
For internal use only.
Full display init function as described in EDT appnote
Definition at line 109 of file gfx_hx8347a.c.
References gfx_write_register(), and udelay().
Referenced by gfx_init().
static void gfx_exit_standby (void) [static]
For internal use only.
Send display commands to exit standby mode.
Definition at line 100 of file gfx_hx8347a.c.
References gfx_clear_register(), gfx_set_register(), and udelay().
Referenced by gfx_init().
static void gfx_reset_display (void) [static]
For internal use only.
Reset display using digital control interface.
Definition at line 90 of file gfx_hx8347a.c.
References gpio_set_value(), and udelay().
Referenced by gfx_init().
static void gfx_set_register (uint8_t address, uint8_t bitmask) [static]
For internal use only.
Read-modify-write shortcut to set bits in a register.
Definition at line 70 of file gfx_hx8347a.c.
References gfx_read_register(), and gfx_write_register().
Referenced by gfx_exit_standby().