display-training: Oscillator Management
Oscillator Management
[Clock Management]
Functions
static __always_inline void osc_enable_internal (uint8_t id)
Enable internal oscillator id.
static void osc_enable_external (uint8_t id)
Enable external oscillator id.
Oscillator Management
static __always_inline void osc_disable (uint8_t id)
Disable oscillator id.
static bool osc_is_running (uint8_t id)
Determine whether oscillator id is running.
static __always_inline void osc_enable (uint8_t id)
Enable oscillator id.
static __always_inline uint32_t osc_get_rate (uint8_t id)
Return the frequency of oscillator id in Hz.
Detailed Description
This group contains functions and definitions related to configuring and enabling/disabling on-chip oscillators.
Function Documentation
void osc_disable (uint8_t id) [static]
Disable oscillator id.
Definition at line 94 of file osc.h.
References osc_read_reg, and osc_write_reg.
Referenced by sysclk_init().
void osc_enable (uint8_t id) [static]
Enable oscillator id.
The startup time and mode value is automatically determined based on definitions in the board code.
Definition at line 48 of file osc.h.
References assert, osc_enable_external(), and osc_enable_internal().
Referenced by sysclk_init().
osc_enable_external (uint8_t id) [inline, static]
Enable external oscillator id.
For internal use only.
Do not call this function directly. Use osc_enable() instead. Also note that this function is only available if the board actually has an external oscillator crystal.
Definition at line 88 of file osc.h.
Referenced by osc_enable().
static __always_inline void osc_enable_internal (uint8_t id) [static]
Enable internal oscillator id.
For internal use only.
Do not call this function directly. Use osc_enable() instead.
Definition at line 59 of file osc.h.
References osc_read_reg, and osc_write_reg.
Referenced by osc_enable().
uint32_t osc_get_rate (uint8_t id) [static]
Return the frequency of oscillator id in Hz.
Definition at line 58 of file osc.h.
References unhandled_case.
Referenced by pll_config_init().
osc_is_running (uint8_t id) [inline, static]
Determine whether oscillator id is running.
Return values:
true Oscillator id is running
false Oscillator id is not running
Definition at line 103 of file osc.h.
References osc_read_reg.
Referenced by sysclk_init().