display-training: Generic Implementation of Graphics Primitives
Generic Implementation of Graphics Primitives
[Graphics driver]
Functions
void gfx_generic_draw_horizontal_line (gfx_coord_t x, gfx_coord_t y, gfx_coord_t length, gfx_color_t color)
Generic implementation of gfx_draw_horizontal_line().
void gfx_generic_draw_vertical_line (gfx_coord_t x, gfx_coord_t y, gfx_coord_t length, gfx_color_t color)
Generic implementation of gfx_draw_vertical_line().
void gfx_generic_draw_line (gfx_coord_t x1, gfx_coord_t y1, gfx_coord_t x2, gfx_coord_t y2, gfx_color_t color)
Generic implementation of gfx_draw_line().
void gfx_generic_draw_rect (gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height, gfx_color_t color)
Generic implementation of gfx_draw_rect().
void gfx_generic_draw_filled_rect (gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height, gfx_color_t color)
Generic implementation of gfx_draw_filled_rect().
void gfx_generic_draw_circle (gfx_coord_t x, gfx_coord_t y, gfx_coord_t radius, gfx_color_t color, uint8_t octant_mask)
Generic implementation of gfx_draw_circle().
void gfx_generic_draw_filled_circle (gfx_coord_t x, gfx_coord_t y, gfx_coord_t radius, gfx_color_t color, uint8_t quadrant_mask)
Generic implementation of gfx_draw_filled_circle().
void gfx_generic_get_pixmap (gfx_color_t *pixmap, gfx_coord_t map_width, gfx_coord_t map_x, gfx_coord_t map_y, gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height)
Generic implementation of gfx_get_pixmap().
void gfx_generic_put_pixmap (const gfx_color_t *pixmap, gfx_coord_t map_width, gfx_coord_t map_x, gfx_coord_t map_y, gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height)
Generic implementation of gfx_put_pixmap().
Detailed Description
This is a library of generic implementations of various graphics primitives. They are meant to simplify the implementation of the low-level graphics driver by providing generic implementations of primitives that aren't directly supported by the hardware.
Function Documentation
void gfx_generic_draw_circle (gfx_coord_t x, gfx_coord_t y, gfx_coord_t radius, gfx_color_t color, uint8_t octant_mask)
Generic implementation of gfx_draw_circle().
Definition at line 206 of file gfx_generic.c.
References gfx_draw_pixel(), GFX_OCTANT0, GFX_OCTANT1, GFX_OCTANT2, GFX_OCTANT3, GFX_OCTANT4, GFX_OCTANT5, GFX_OCTANT6, and GFX_OCTANT7.
void gfx_generic_draw_filled_circle (gfx_coord_t x, gfx_coord_t y, gfx_coord_t radius, gfx_color_t color, uint8_t quadrant_mask)
Generic implementation of gfx_draw_filled_circle().
Definition at line 258 of file gfx_generic.c.
References gfx_draw_pixel(), gfx_draw_vertical_line, GFX_QUADRANT0, GFX_QUADRANT1, GFX_QUADRANT2, and GFX_QUADRANT3.
void gfx_generic_draw_filled_rect (gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height, gfx_color_t color)
Generic implementation of gfx_draw_filled_rect().
Definition at line 142 of file gfx_generic.c.
References gfx_duplicate_pixel(), gfx_max_x, gfx_max_y, gfx_min_x, gfx_min_y, and gfx_set_limits().
void gfx_generic_draw_horizontal_line (gfx_coord_t x, gfx_coord_t y, gfx_coord_t length, gfx_color_t color)
Generic implementation of gfx_draw_horizontal_line().
Definition at line 45 of file gfx_generic.c.
References gfx_draw_filled_rect.
void gfx_generic_draw_line (gfx_coord_t x1, gfx_coord_t y1, gfx_coord_t x2, gfx_coord_t y2, gfx_color_t color)
Generic implementation of gfx_draw_line().
Definition at line 57 of file gfx_generic.c.
References gfx_draw_line_pixel(), gfx_height, gfx_set_bottom_right_limit(), and gfx_width.
void gfx_generic_draw_rect (gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height, gfx_color_t color)
Generic implementation of gfx_draw_rect().
Definition at line 131 of file gfx_generic.c.
References gfx_draw_horizontal_line, and gfx_draw_vertical_line.
void gfx_generic_draw_vertical_line (gfx_coord_t x, gfx_coord_t y, gfx_coord_t length, gfx_color_t color)
Generic implementation of gfx_draw_vertical_line().
Definition at line 51 of file gfx_generic.c.
References gfx_draw_filled_rect.
void gfx_generic_get_pixmap (gfx_color_t * pixmap, gfx_coord_t map_width, gfx_coord_t map_x, gfx_coord_t map_y, gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height)
Generic implementation of gfx_get_pixmap().
Definition at line 318 of file gfx_generic.c.
References assert, gfx_copy_pixels_from_screen(), gfx_max_x, gfx_max_y, gfx_min_x, gfx_min_y, gfx_set_bottom_right_limit(), and gfx_set_top_left_limit().
void gfx_generic_put_pixmap (const gfx_color_t * pixmap, gfx_coord_t map_width, gfx_coord_t map_x, gfx_coord_t map_y, gfx_coord_t x, gfx_coord_t y, gfx_coord_t width, gfx_coord_t height)
Generic implementation of gfx_put_pixmap().
Definition at line 409 of file gfx_generic.c.
References assert, gfx_copy_pixels_to_screen(), gfx_max_x, gfx_max_y, gfx_min_x, gfx_min_y, gfx_set_bottom_right_limit(), and gfx_set_top_left_limit().