display-training: drivers/gfx/hx8347a/hx8347a_xmega.h File Reference
drivers/gfx/hx8347a/hx8347a_xmega.h File Reference
AVR XMEGA-specific bits of the HX8347A display driver.
#include <board/hx8347a.h>
Defines
#define gfx_select_chip() (GFX_CS_PORT.OUTCLR = GFX_CS_PINMASK)
Functions
static void gfx_select_register (uint8_t address)
static void gfx_write_register (uint8_t address, uint8_t value)
static uint8_t gfx_read_register (uint8_t address)
static void gfx_init_comms (void)
static void gfx_setup_interface (void)
void gfx_duplicate_pixel (gfx_color_t color, uint32_t count)
Draw multiple pixels all having the same color.
void gfx_copy_pixels_to_screen (const gfx_color_t *pixels, uint32_t count)
Copy a block of pixels from data memory to screen.
void gfx_copy_progmem_pixels_to_screen (const gfx_color_t __progmem_arg *pixels, uint32_t count)
Copy a block of pixels from program memory to screen.
void gfx_copy_hugemem_pixels_to_screen (const hugemem_ptr_t pixels, uint32_t count)
Copy a block of pixels from hugemem to screen.
void gfx_copy_pixels_from_screen (gfx_color_t *pixels, uint32_t count)
Copy a block of pixels from screen to data memory.
Detailed Description
AVR XMEGA-specific bits of the HX8347A display driver.
Copyright (C) 2009 Atmel Corporation. All rights reserved.
Definition in file hx8347a_xmega.h.
Define Documentation
#define gfx_select_chip () (GFX_CS_PORT.OUTCLR = GFX_CS_PINMASK)
Todo:
remove dependency on toolchain header files.
Definition at line 50 of file hx8347a_xmega.h.
Referenced by gfx_copy_hugemem_pixels_to_screen(), gfx_copy_pixels_from_screen(), gfx_copy_pixels_to_screen(), gfx_copy_progmem_pixels_to_screen(), gfx_duplicate_pixel(), gfx_read_register(), gfx_select_register(), and gfx_write_register().
Function Documentation
static void gfx_init_comms (void) [static]
For internal use only.
Initialize communication interface to display.
Definition at line 148 of file hx8347a_xmega.h.
References SYSCLK_DMA, sysclk_enable_module(), SYSCLK_PORT_D, SYSCLK_PORT_GEN, and SYSCLK_USART1.
Referenced by gfx_init().
static uint8_t gfx_read_register (uint8_t address) [static]
For internal use only.
Send display command to read a byte from a specific register.
Definition at line 95 of file hx8347a_xmega.h.
References gfx_select_chip, and gfx_select_register().
Referenced by gfx_clear_register(), gfx_set_orientation(), and gfx_set_register().
static void gfx_select_register (uint8_t address) [static]
For internal use only.
Send display command to select register address.
Definition at line 74 of file hx8347a_xmega.h.
References gfx_select_chip.
Referenced by gfx_copy_hugemem_pixels_to_screen(), gfx_copy_pixels_from_screen(), gfx_copy_pixels_to_screen(), gfx_copy_progmem_pixels_to_screen(), gfx_duplicate_pixel(), gfx_read_register(), and gfx_write_register().
static void gfx_setup_interface (void) [static]
For internal use only.
Setup digital control interface to display.
Definition at line 177 of file hx8347a_xmega.h.
References PORT_DIR_INPUT, PORT_DIR_OUTPUT, PORT_INIT_HIGH, and port_select_gpio_pin().
Referenced by gfx_init().
static void gfx_write_register (uint8_t address, uint8_t value) [static]
For internal use only.
Send display command to write a byte to a specific register.
Definition at line 84 of file hx8347a_xmega.h.
References gfx_select_chip, and gfx_select_register().
Referenced by gfx_clear_register(), gfx_display_init_all(), gfx_set_bottom_right_limit(), gfx_set_orientation(), gfx_set_register(), and gfx_set_top_left_limit().